<% config = YAML.load_file('/etc/katello/katello.yml') rescue nil
  def find_db(config, env)
    db = nil
    if config
      if config[env] && config[env]['database']
        db = config[env]['database']
      elsif config['common'] && config['common']['database']
        db = config['common']['database']
      end
    end
    return db.collect {|k,v| "  #{k}: #{v}"}.sort.join("\n") if db
    nil
  end
%>


development:
  adapter: postgresql
  username: katello
  password: katello
  database: katello
  host: localhost
  encoding: UTF8
